swagger: "2.0"
info:
  description: "Demo by Yonatan Riaznov"
  version: "1.0.0"
  title: "Swagger PHP Demo"
  contact:
    email: "yonatan.r@bidalgo.com"
basePath: "/api/demo/public"
tags:
  - name: "employee"
    description: "Bidalgo employees"
schemes:
  - "http"
paths:
  /employee:
    post:
      tags:
        - "employee"
      summary: "Add a new employee to Bidalgo"
      description: ''
      operationId: "addEmployee"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Employee object that needs to be added to the store"
          required: true
          schema:
            $ref: '#/definitions/Employee'
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "Invalid input"
    put:
      tags:
        - "employee"
      summary: "Update an existing employee"
      description: ''
      operationId: "updateEmployee"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Employee object that needs to be added to the store"
          required: true
          schema:
            $ref: '#/definitions/Employee'
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Employee not found"
        405:
          description: "Validation exception"
  /employee/{employeeId}:
    get:
      tags:
        - "employee"
      summary: "Find employee by ID"
      description: "Returns a single employee"
      operationId: "getEmployeeById"
      produces:
        - "application/json"
      parameters:
        - name: "employeeId"
          in: "path"
          description: "ID of employee to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: '#/definitions/Employee'
        400:
          description: "Invalid ID supplied"
        404:
          description: "Employee not found"
    delete:
      tags:
        - "employee"
      summary: "Delete Employee"
      description: ''
      operationId: "deleteEmployee"
      produces:
        - "application/json"
      parameters:
        - name: "employeeId"
          in: "path"
          description: "Employee id to delete"
          required: true
          type: "integer"
          format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Employee not found"
definitions:
  Employee:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      firstName:
        type: "string"
      lastName:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"